### ISSUE TITLE
Release 0.4.0

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#12]
@rodolfobandeira are you interested in helping out?

If yes, I'll add you to co-maintainers and will need your rubygems e-mail to add you to gem owners

**Comment by dblock** [comment]
Need to do #13 first.

**Comment by rodolfobandeira** [comment]
For sure, I'll mail you directly right now. Thanks!

**Comment by rodolfobandeira** [comment]
Done with #13
