### ISSUE TITLE
Bump 0.3.4 to 0.4.0 and add UPGRADING

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#13]
The change in #9 was actually an interface change as before you could handle `Faraday::ClientError` but now it's an `IEX::Errors::ClientError`.

* Bump next version to 0.4.0 from 0.3.4 to make next release a major update.
* Add an UPGRADING document that describes the interface change(s) ala https://github.com/slack-ruby/slack-ruby-client/blob/master/UPGRADING.md

@rodolfobandeira Want to PR this?

**Comment by rodolfobandeira** [comment]
I'll take care of it! Thanks!
