### ISSUE TITLE
Implement Sector Performance

### ISSUE THREAD

**Issue by rodolfobandeira** [dblock/iex-ruby-client#31]
Reference: https://iextrading.com/developer/docs/#sector-performance

**Comment by gil27** [comment]
@rodolfobandeira, Is it gonna be for the current day?

**Comment by rodolfobandeira** [comment]
Hey @gil27 

I'm not sure on which frequency it updates this endpoint, but by the time I'm writing this, the `lastUpdated` timestamp is actually representing **October 1, 8pm**. So, looks like it at least runs once a day. For your implementation though, you won't need to pass any parameter. That said, this looks to be a great challenge to address since the complexity is low. Please let me know if you have any questions!

Raw response: https://api.iextrading.com/1.0/stock/market/sector-performance

**Comment by gil27** [comment]
Awesome, I will put some work on it
