### ISSUE TITLE
Double check "largest-trades" behavior when multiple trades are returned

### ISSUE THREAD

**Issue by rodolfobandeira** [dblock/iex-ruby-client#35]
For next week, while trading hours is running (~9:45am - 4:00pm), confirm how the `largest-trades` endpoint behaves on the following:

- How it orders the list? From largest trades to lower?
- How many elements are displayed on this list?
- Is it indeed a list or just shows the largest trade for that day? (If that is just one, the IEX documentation is wrong since it shows an array list)
- If it returns a list of elements indeed, fix tests and review our code to make sure it handles multiple trades;

cc: @dblock @gil27

**Comment by gil27** [comment]
Hey @rodolfobandeira, it is a list. I don't remember how it orders it but it is a list. On tests I've use `trades.first` to check values and also have a test to check the quantity of results.

I think my mistake was in README.md where I didn't make it clear that it was a list.

**Comment by gil27** [comment]
Nice @rodolfobandeira, if there is no problem I will fix the README.md ok?

**Comment by rodolfobandeira** [comment]
@gil27 Sorry, just saw your msg now. Please check #36

**Comment by gil27** [comment]
Haha, it's ok👍 I've post it a few minutes ago. =)
