### ISSUE TITLE
Migrate to IEX cloud apis

### ISSUE THREAD

**Issue by bingxie** [dblock/iex-ruby-client#40]
Because 

> On June 1, 2019, IEX API will sunset all non-IEX data. IEX Cloud, a non-Exchange platform, will continue to provide access to third-party data sources.
see here: https://iextrading.com/developer/

I am migrating this client to the new IEX cloud APIs. 
Which includes: 

1. Use the new IEX cloud URL and token
2. Use the sandbox data for specs
3. Update the crypto quote API
4. Update README

I wish I can create a Pull Request for review in a week.

**Comment by dblock** [comment]
Thank you @bingxie, looking forward to your PR! LMK if you need any help.

**Comment by dblock** [comment]
#42

**Comment by dblock** [comment]
Closed via https://github.com/dblock/iex-ruby-client/pull/42
