### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#48]
@bingxie Want to take care of it? Follow https://github.com/dblock/iex-ruby-client/blob/master/RELEASING.md

**Comment by bingxie** [comment]
Thanks @dblock  I would like to take this and I will also do some manual test in my side project.

**Comment by dblock** [comment]
Go for it @bingxie!

**Comment by bingxie** [comment]
I have released the version 1.0.0 and tested on my own side project, and I will notify the IEX cloud to notify them there is a new ruby client version.

**Comment by dblock** [comment]
Awesome, thank you.
