### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by suhanlee** [dblock/iex-ruby-client#54]
Thank you for your work!

I think latest version is not 1.0.1 on rubygems site (current is 1.0.0)
Could you deploy 1.0.1 to rubygems?
<img width="744" alt="스크린샷 2019-07-07 오전 12 53 50" src="https://user-images.githubusercontent.com/2666166/60758452-bcb0a880-a051-11e9-9c00-6290b6c62c93.png">

**Comment by dblock** [comment]
Maybe @bingxie or any other maintainer wants to cut a release...

**Comment by bingxie** [comment]
Ok, I will try to get my branch merged and release a new version this week.

**Comment by bingxie** [comment]
Hi, @suhanlee I just released the version 1.0.1, you can use it now.
