### ISSUE TITLE
uninitialized constant IEX::Resources::OHLC

### ISSUE THREAD

**Issue by investment-radar** [dblock/iex-ruby-client#6]
I put the gem into my rails project when I call `ohlc = IEX::Resources::OHLC.get('MSFT')` I got `NameError (uninitialized constant IEX::Resources::OHLC)` 

My versions:
ruby 2.5.0
rails 5.2

I looked at the source code but I could not figure it out.

**Comment by dblock** [comment]
That's because that hasn't been released yet :) See https://github.com/dblock/iex-ruby-client/blob/master/CHANGELOG.md.

You can do `github: 'dblock/iex-ruby-client'` in Gemfile for now. I'll cut a release soon.

**Comment by investment-radar** [comment]
I see, thanks.

**Comment by dblock** [comment]
https://github.com/dblock/iex-ruby-client/issues/7

**Comment by dblock** [comment]
This was released FYI, thanks @jromanovs
