### ISSUE TITLE
ISIN Mapping request

### ISSUE THREAD

**Issue by bguban** [dblock/iex-ruby-client#62]
Hi. Is it possible to request ISIN Mapping using this gem? I tried to use the `post` method of the library
```
client.post("ref-data/isin", isin: ['US0378331005'])
```
but it returned an error `IEX::Errors::ClientError: "token" is not allowed`. I'm sure that the specified token is correct because direct request via Faraday works perfectly. I tried to put my token directly via params, but the result is the same.
I noticed that configuration can use only `publishable_token`. Is it possible to set up the library with a private token?

**Comment by dblock** [comment]
I think you're asking for https://github.com/dblock/iex-ruby-client/issues/43. I am happy to help with the implementation, we need to add that to the configuration, use it in the right places, etc.

**Comment by bguban** [comment]
Thanks @dblock. I made the https://github.com/dblock/iex-ruby-client/pull/63 PR. So could you take a look?

**Comment by bguban** [comment]
The problem was solved https://github.com/dblock/iex-ruby-client/pull/63
