### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#7]
Follow https://github.com/dblock/iex-ruby-client/blob/master/RELEASING.md

Thanks @jromanovs !

**Comment by jromanovs** [comment]
Could you please make some directions for me how to proceed further. I had completed all steps mentioned in RELEASING.md. Should I create pull request?

**Comment by dblock** [comment]
Did you do them in your own tree? In which case just merge your changes to master here, no need to PR but you can also PR if you want and self-merge. For next time check out the root fo the fork and just make releases from it.

**Comment by dblock** [comment]
For your code changes make pull requests.
Feel free to review/approve/merge/reject other people's changes.

**Comment by jromanovs** [comment]
Done

**Comment by dblock** [comment]
🙇
