### ISSUE TITLE
company_logo url issue

### ISSUE THREAD

**Issue by Dmoment** [dblock/iex-ruby-client#76]
logo=client.logo('MSFT')
logo.url --->In documentation it is mentioned to return **#'https://storage.googleapis.com/iex/api/logos/MSFT.png'** but actually it is fetching some encrypted gibberish url -->/**pp7/saeiuho..noxgoctrogocplsgsioml:/aho/pT.Ftgp3-e/egSastMiglldo/**

**Comment by dblock** [comment]
This is expected, data in the sandbox environment is scrambled, see https://github.com/dblock/iex-ruby-client#sandbox-environment. I had given feedback to IEX that this is confusing already a couple of times ;)
