### ISSUE TITLE
Release v. Next

### ISSUE THREAD

**Issue by dblock** [dblock/iex-ruby-client#80]
Add your +1 if you want/need a release.

**Comment by dblock** [comment]
There's a fix for #79 in #71.

**Comment by agrberg** [comment]
I released 1.3.0

**Comment by agrberg** [comment]
Going to release v2.0.0 tomorrow 7/24/22 unless told otherwise 🚀

**Comment by agrberg** [comment]
v2.0 fresh off the presses 📰

**Comment by maxemitchell** [comment]
@dblock Could v2.0.1 get released? Thanks in advance

**Comment by dblock** [comment]
calling @agrberg! :) I will try to release over the weekend if I get to a computer otherwise

**Comment by agrberg** [comment]
Howdy dblock. Sorry I won't have the opportunity to handle this. Always a
bit more to do for the start up.

**Comment by dblock** [comment]
I released 2.1.0.
