### ISSUE TITLE
Why do the prices change at every call?

### ISSUE THREAD

**Issue by chanp-ark** [dblock/iex-ruby-client#81]
Why do the prices change at every call?

when I call, 

`client.ohlc(ticker_symbol).close.price` for the closing price

or 

`client.quote(ticker_symbol).latest_price` for the current price,

it changes every time. Anyone know what?

**Comment by dblock** [comment]
Maybe a question to IEX?

**Comment by chanp-ark** [comment]
In case anyone has the same question in the future, data returned from the Sandbox API calls is scrambled

**Comment by dblock** [comment]
Oh so this is a feature of the sandbox environment?

**Comment by dblock** [comment]
Care to PR a small update to https://github.com/dblock/iex-ruby-client#sandbox-environment that says something like "and results, such as closing market prices, vary on every call" ?

**Comment by dblock** [comment]
https://github.com/dblock/iex-ruby-client/pull/83
