### ISSUE TITLE
update historical price in Readme.md file 

### ISSUE THREAD

**Issue by UmerFrooq** [dblock/iex-ruby-client#96]
historial_prices = client.historical_prices('MSFT', {range: 'date', date: Date.parse('2020-09-30'), chartByDay: 'true'}) # One day of data
 i have correct this it actually have colon issue in Date.parse('2020-09-30)'  and it should be Date.parse('2020-09-30') this.

**Comment by dblock** [comment]
Please make a PR?

**Comment by UmerFrooq** [comment]
sure sir

**Comment by dblock** [comment]
Closed via #97
